# steps:
# # Build the image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'LOCATION-docker.pkg.dev/fine-slice-463202-g1/gcr_test/gcr_test/europe-west1:$COMMIT_SHA', '.']
# # Push the image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'LOCATION-docker.pkg.dev/fine-slice-463202-g1/gcr_test/gcr_test/gcr-test:$COMMIT_SHA']
# # Deploy image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: 
#     - 'run'
#     - 'deploy'
#     - 'gcr-test'
#     - '--image'
#     - 'LOCATION-docker.pkg.dev/fine-slice-463202-g1/gcr_test/gcr_test/gcr-test:$COMMIT_SHA'
#     - '--region'
#     - 'SERVICE_REGION'
# images:
# - 'LOCATION-docker.pkg.dev/fine-slice-463202-g1/gcr_test/gcr_test/gcr-test:$COMMIT_SHA'

steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE', '--region', 'SERVICE_REGION']
images:
- 'LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE'
